### ISSUE TITLE
Extract documentation from ObamaPhony/node-app

### ISSUE THREAD

**Issue by ghost** [ObamaPhony/rest-api#3]
Lacking a REST API at the time, I had to whip up one really quickly so I didn't follow the documentation we wrote here as I didn't have the time to modify the documentation.

Now, we should extract documentation from the existing Node.js-based REST API routes for use in the Go-based REST API.

**Comment by shymega** [comment]
Hello,

Saleem Rashid notifications@github.com writes:

> Lacking a REST API at the time, I had to whip up one really quickly
> so I didn't follow the documentation we wrote here as I didn't have
> the time to modify the documentation.
> 
> Now, we should extract documentation from the existing Node.js-based
> REST API routes for use in the Go-based REST API.

Agreed, I will do that.

Thanks.

## 

Regards,
Dom Rodriguez

**Comment by shymega** [comment]
Closing in favour of [this](https://github.com/ObamaPhony/java-app).
